var akanArray = [
    {
        Sunday:"Kwasi",
        Monday:"Kwadwo",
        Tuesday:"Kwabena",
        Wednesday:"Kwaku",
        Thurday:"Yaw",
        Friday:"Kofi",
        Saturday:"Kwame"
    }, 
    {
        Sunday:"Akosua",
        Sunday:"Adwoa",
        Monday:"Abenaa",
        Tuesday:"Kwabena",
        Wednesday:"Akua",
        Thurday:"Yaa",
        Friday:"Afua",
        Saturday:"Ama"
    }
]